### ISSUE TITLE
Player "floats" if the player is wider than the window

### ISSUE THREAD

**Issue by ramezn** [michielkoning/abuses#3]
I think this is related to the scrolling behavior on mobile.  From a friend:

"On IOS/Chrome it appears like the video just floats above the scrolling list, instead of having the list be contained in a distinct object below that it scrolls within. You can then see the list semitransparently at the top and lower boundaries of the video. I haven't found explicit UX failures with this yet, but this type of model can cause sometimes because the browser is having to track and render layers in ways that are more complex than when things operate in distinct regions."  

"It's caused by the width of the page being wider than the browser itself".

**Comment by michielkoning** [comment]
This was due to some longer text in the description that could not be cut of (like long links from facebook). For now I removed the longer links.
